using System;
using System.Collections.Generic;

namespace ZapretDPI.Services;

public static class LocalizationService
{
    public static string CurrentLanguage { get; private set; } = "tr";

    public static event Action? LanguageChanged;

    private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
    {
        ["tr"] = new()
        {
            ["App_Title"] = "ZapretDPI-TR",
            ["Nav_Overview"] = "Genel Bakış",
            ["Nav_Engine"] = "DPI Yönlendirme",
            ["Nav_Rules"] = "Paket Kuralları",
            ["Nav_Filters"] = "Filtreler & Domainler",
            ["Nav_Dns"] = "DNS & DoH",
            ["Nav_Lan"] = "Ağ Paylaşımı",
            ["Nav_Analysis"] = "ISS Analizi",
            ["Nav_Console"] = "Konsol & Loglar",
            ["Nav_Recovery"] = "Kurtarma",
            ["Nav_About"] = "Hakkında",
            ["Footer_Core"] = "DPI Çekirdeği",
            ["Footer_Version"] = "Yazılım Sürümü",

            ["UI_NavOverview"] = "Genel Bakış",
            ["UI_NavRules"] = "Paket Kuralları",
            ["UI_NavFilters"] = "Filtreler & Domainler",
            ["UI_NavDns"] = "DNS & DoH",
            ["UI_NavLan"] = "Ağ Paylaşımı",
            ["UI_NavAnalysis"] = "ISS Analizi",
            ["UI_NavRecovery"] = "Kurtarma",
            ["UI_NavAbout"] = "Hakkında",
            ["UI_LblFooterVersionHeader"] = "Yazılım Sürümü",
            ["UI_LblOverviewTitle"] = "Genel Bakış",
            ["UI_TxtDashboardSubtitle"] = "ZapretDPI-TR hazır • Başlatmaya hazır",
            ["UI_LblPillRouting"] = "Etkin yönlendirme",
            ["UI_TxtRoutingStatus"] = "Kurulmamış",
            ["UI_LblPillEngine"] = "DPI yöntemi",
            ["UI_TxtEngineStatus"] = "Zapret2 (LUA)",
            ["UI_LblPillService"] = "Çalışan servis",
            ["UI_TxtServiceStatus"] = "0 servis",
            ["UI_LblPillDns"] = "DNS / DoH",
            ["UI_TxtDnsStatus"] = "Cloudflare (1.1.1.1)",
            ["UI_LblPillWinDivert"] = "WinDivert bileşeni",
            ["UI_TxtWinDivertStatus"] = "Yüklü (v1.0.4)",
            ["UI_LblPillLan"] = "Ağ Paylaşımı",
            ["UI_TxtLanStatus"] = "Kapalı",
            ["UI_LblOverviewActiveProfileTitle"] = "Kullanılacak DPI Profili",
            ["UI_LblOverviewActiveProfileDesc"] = "Standart başlatma ve Windows Servisi bu seçili stratejiyle çalışır.",
            ["UI_LblActionSectionTitle"] = "Yönlendirme Kurulumu",
            ["UI_LblActionSectionDesc"] = "Zapret'in kullandığı Windows yönlendirme ve DPI bypass bileşenlerini başlatır veya kurar.",
            ["UI_LblQuickStartTitle"] = "Standart Başlatma",
            ["UI_LblQuickStartDesc"] = "Seçili strateji profili ile DPI bypass oturumunu başlatır.",
            ["UI_BtnQuickStart"] = "Yükleniyor...",
            ["UI_LblQuickServiceTitle"] = "Windows Servisi (Otomatik Başlat)",
            ["UI_LblQuickServiceDesc"] = "Windows ile birlikte arka planda sessizce otomatik çalışan sistem servisi.",
            ["UI_BtnQuickService"] = "Yükleniyor...",
            ["UI_LblQuickDnscryptTitle"] = "Şifreli DNS (DNSCrypt-proxy)",
            ["UI_LblQuickDnscryptDesc"] = "ISS kaynaklı DNS zehirlenmesine karşı şifreli DNS servisini kurar.",
            ["UI_BtnQuickDnscrypt"] = "Yükleniyor...",
            ["UI_LblRulesTitle"] = "Paket Kuralları & Strateji",
            ["UI_LblRulesDesc"] = "Türkiye'deki ISS'ler için test edilmiş hazır stratejileri veya özel LUA desync parametrelerini seçin.",
            ["UI_LblFilterMode"] = "Filtreleme Modu",
            ["UI_CmbFilterOff"] = "Kapalı (Tüm internet trafiğine uygula)",
            ["UI_CmbFilterAuto"] = "Auto (Zapret dinamik autohostlist oluşturur)",
            ["UI_CmbFilterManual"] = "Manuel ('hostlist.txt' içindeki domainler)",
            ["UI_LblPresetTitle"] = "Hazır Strateji Profili",
            ["UI_LblActiveParams"] = "Aktif LUA Parametreleri:",
            ["UI_BtnSaveStrategy"] = "Stratejiyi Kaydet",
            ["UI_LblFiltersTitle"] = "Filtreler & Domain Listeleri",
            ["UI_LblHostlistTitle"] = "DPI Uygulanacak Domainler",
            ["UI_BtnSaveHostlist"] = "Listeyi Kaydet",
            ["UI_LblExcludelistTitle"] = "Hariç Tutulacak Domainler",
            ["UI_BtnSaveExcludelist"] = "Hariç Listesini Kaydet",
            ["UI_LblDnsTitle"] = "DNS Yapılandırması & Güvenlik",
            ["UI_LblDnsDesc"] = "DNS zehirlenmesini tespit edin, Google DoH veya DNSCrypt-proxy ile şifreleyin.",
            ["UI_LblPoisonCheckTitle"] = "DNS Zehirlenmesi Kontrolü",
            ["UI_LblPoisonCheckDesc"] = "ISS'nin Discord ve engelli sitelerin IP adreslerini sahte yönlendirmelere yönlendirip yönlendirmediğini test eder.",
            ["UI_TxtTestDnsPoison"] = "DNS Zehirlenmesini Şimdi Test Et",
            ["UI_LblQuickSwitcherTitle"] = "Hızlı DNS Değiştirici",
            ["UI_BtnSetGoogleDns"] = "Google DNS (8.8.8.8 / 8.8.4.4) [Önerilen]",
            ["UI_BtnSetCloudflareDns"] = "Cloudflare (1.1.1.1 / 1.0.0.1)",
            ["UI_BtnSetAdguardDns"] = "AdGuard DNS (94.140.14.14 / 94.140.15.15)",
            ["UI_BtnResetDnsDhcp"] = "Otomatiğe Al (DHCP Sıfırla)",
            ["UI_LblLanTitle"] = "Ağdaki Cihazlarla Paylaş (LAN)",
            ["UI_LblLanDesc"] = "PlayStation, Xbox, Akıllı TV gibi cihazların Zapret üzerinden DPI aşımı yapmasını sağlayın.",
            ["UI_LblRouterDesc"] = "Npcap paket yakalama sürücüsü ile yerel ağ trafiğini otomatik olarak Zapret'e yönlendirir.",
            ["UI_BtnToggleLanShare"] = "LAN Paylaşımını Başlat",
            ["UI_LblAnalysisTitle"] = "ISS Blok Analizi (Blockcheck2)",
            ["UI_LblAnalysisDesc"] = "İnternet Servis Sağlayıcınızın uyguladığı DPI sansür tipini otomatik olarak tarayın.",
            ["UI_LblAnalysisCardTitle"] = "Otomatik DPI Analiz Testi",
            ["UI_LblAnalysisCardDesc"] = "Analiz işlemi 5-10 dakika sürebilir. Test tamamlandığında çalışan strateji otomatik kaydedilir.",
            ["UI_LblScanMode"] = "Tarama Modu:",
            ["UI_RbScanFast"] = "Hızlı (İlk çalışanda dur)",
            ["UI_RbScanSmart"] = "SmartScan (10 adet bul)",
            ["UI_RbScanDeep"] = "Derin (Tamamı)",
            ["UI_TxtStartAnalysis"] = "ISS Analizini Başlat",
            ["UI_TxtAnalysisStatus"] = "Hazır.",
            ["UI_LblRecoveryTitle"] = "Kurtarma & Sistem Temizliği",
            ["UI_LblRecoveryDesc"] = "Sistemdeki tüm DPI servislerini, WinDivert sürücülerini kaldırın ve DNS ayarlarını fabrika ayarlarına döndürün.",
            ["UI_LblResetTitle"] = "Tam Sistem Sıfırlama & Temizlik",
            ["UI_LblRecoveryListHeader"] = "Aşağıdaki işlemler yapılarak sistem fabrika ayarlarına döndürülür:",
            ["UI_LblRecoveryItem1"] = "ZapretService ve dnscrypt-proxy arka plan servislerini durdurur ve siler.",
            ["UI_LblRecoveryItem2"] = "WinDivert ve Monkey paket yönlendirme sürücülerini sistemden kaldırır.",
            ["UI_LblRecoveryItem3"] = "Tüm ağ bağdaştırıcı DNS ayarlarını otomatiğe (DHCP) çeker.",
            ["UI_LblRecoveryItem4"] = "Windows DNS çözümleyici önbelleğini (flushdns) temizler.",
            ["UI_TxtFullCleanup"] = "Tüm Kalıntıları ve Servisleri Temizle",
            ["UI_LblAboutTitle"] = "Hakkında",
            ["UI_LblAboutSubtitle"] = "ZapretDPI-TR sürüm bilgileri, sistem ayrıntıları ve lisanslar.",
            ["UI_LblAboutDescription"] = "Windows üzerindeki ağ yönlendirme, DPI yöntemleri (Zapret2 LUA), DNS güvenliği ve otomatik ISS analizini tek yerden yöneten modern masaüstü yönetim aracı.",
            ["UI_LblAboutPlatformCardTitle"] = "Platform & Sistem",
            ["UI_LblAboutPlatformTitle"] = "Platform:",
            ["UI_TxtAboutPlatform"] = "Microsoft Windows",
            ["UI_LblAboutArchTitle"] = "Mimari:",
            ["UI_TxtAboutArch"] = "64-Bit (X64)",
            ["UI_LblAboutRuntimeTitle"] = "Çalışma Zamanı:",
            ["UI_TxtAboutRuntime"] = ".NET 10.0 WPF",
            ["UI_LblAboutLanguageTitle"] = "Arayüz Dili:",
            ["UI_TxtAboutLanguage"] = "Türkçe",
            ["UI_LblAboutDpiCardTitle"] = "DPI Çekirdeği & Ağ",
            ["UI_LblAboutCoreTitle"] = "DPI Çekirdeği:",
            ["UI_TxtAboutCore"] = "Zapret2 (LUA)",
            ["UI_LblAboutDriverTitle"] = "Paket Sürücüsü:",
            ["UI_LblAboutDnsTitle"] = "Şifreli DNS:",
            ["UI_LblAboutLanTitle"] = "Ağ Paylaşımı:",
            ["UI_LblAboutLicenseHeader"] = "Lisans & Açık Kaynak Bildirimi",
            ["UI_LblAboutLicense"] = "ZapretDPI-TR açık kaynaklı bir yazılımdır ve MIT Lisansı altında dağıtılmaktadır. Proje; Zapret2 (WinWS2), WinDivert, dnscrypt-proxy ve go-pcap2socks açık kaynaklı bileşenlerinden güç alır. Tüm üçüncü taraf kütüphane ve sürücülerin telif hakları kendi bağımsız geliştiricilerine aittir.",
            ["UI_TxtOpenRepo"] = "Proje Deposu (GitHub)",
            ["UI_TxtCheckUpdatesAbout"] = "Güncellemeleri Denetle",

            ["Overview_Title"] = "Genel Bakış",
            ["Overview_ReadySubtitle"] = "ZapretDPI-TR hazır • Başlatmaya hazır",
            ["Overview_ServiceSubtitle"] = "ZapretService devrede • Ağ koruması aktif",
            ["Overview_ProcessSubtitle"] = "Zapret işlemi çalışıyor • Trafik yönlendiriliyor",
            ["Overview_StoppingSubtitle"] = "Durduruluyor...",
            ["Overview_StartingSubtitle"] = "Başlatılıyor...",

            ["Pill_Routing"] = "Etkin yönlendirme",
            ["Pill_Engine"] = "DPI yöntemi",
            ["Pill_Service"] = "Çalışan servis",
            ["Pill_Dns"] = "DNS / DoH",
            ["Pill_WinDivert"] = "WinDivert bileşeni",
            ["Pill_Lan"] = "Ağ Paylaşımı",

            ["Status_NotInstalled"] = "Kurulmamış",
            ["Status_ServiceActive"] = "Servis Aktif",
            ["Status_ManualActive"] = "Manuel Aktif",
            ["Status_Installed"] = "Yüklü (v1.0.4)",
            ["Status_Active"] = "Aktif",
            ["Status_Off"] = "Kapalı",
            ["Status_Loading"] = "Yükleniyor...",
            ["Status_ZeroService"] = "0 servis",
            ["Status_OneProcess"] = "1 işlem",
            ["Status_MultipleServices"] = "{0} Servis (Zapret + DNS)",
            ["Status_OneServiceZapret"] = "1 Servis (ZapretService)",
            ["Status_OneServiceDnscrypt"] = "1 Servis (DNSCrypt)",
            ["Status_StandardDoh"] = "Standart / DoH",
            ["Status_DnscryptActive"] = "DNSCrypt (127.0.0.1)",

            ["Action_SectionTitle"] = "Yönlendirme Kurulumu",
            ["Action_SectionDesc"] = "Zapret'in kullandığı Windows yönlendirme ve DPI bypass bileşenlerini başlatır veya kurar.",

            ["Action_QuickStartTitle"] = "Standart Başlatma",
            ["Action_QuickStartDesc"] = "Önerilen yöntem. Çift profilli (Discord + Web) DPI bypass oturumunu başlatır.",
            ["Btn_StartZapret"] = "Zapret'i Başlat",
            ["Btn_StopZapret"] = "Zapret'i Durdur",

            ["Action_ServiceTitle"] = "Windows Servisi (Otomatik Başlat)",
            ["Action_ServiceDesc"] = "Windows ile birlikte arka planda sessizce otomatik çalışan sistem servisi.",
            ["Btn_InstallService"] = "Servis Olarak Kur",
            ["Btn_RemoveService"] = "Servisi Kaldır",

            ["Action_DnscryptTitle"] = "Şifreli DNS (DNSCrypt-proxy)",
            ["Action_DnscryptDesc"] = "ISS kaynaklı DNS zehirlenmesine karşı şifreli DNS servisini kurar.",
            ["Btn_InstallDnscrypt"] = "DNSCrypt Kur",
            ["Btn_RemoveDnscrypt"] = "DNSCrypt Kaldır",

            ["Dns_DnscryptTitle"] = "Şifreli DNS Sunucusu (DNSCrypt)",
            ["Dns_DnscryptDesc"] = "DNSCrypt aktifken kullanılacak şifreli DNS sunucusunu seçin.",
            ["Console_Title"] = "Canlı Konsol (Log Akışı)",
            ["Console_Desc"] = "Zapret servisinden ve motorundan gelen son olayları buradan takip edebilirsiniz.",
            ["Console_BtnClear"] = "Logları Temizle",
            ["Console_BtnOpenDir"] = "Log Dizinini Aç",

            ["Engine_Title"] = "DPI Yönlendirme & Motor",
            ["Engine_Desc"] = "Zapret çalışma motorunu ve ağ filtreleme kurallarını yapılandırın.",
            ["Engine_Selection"] = "DPI Motoru Seçimi",
            ["Engine_Zapret2"] = "Zapret2 v1.0.4 (Yeni LUA Motoru - Tavsiye Edilen)",
            ["Engine_Zapret2Desc"] = "Yeni LUA filtreleme modülleri ve çoklu profil (Discord + web) desteği sağlar.",

            ["Engine_FilterMode"] = "Filtreleme Modu",
            ["Filter_Auto"] = "Auto (Zapret dinamik autohostlist oluşturur)",
            ["Filter_Manual"] = "Manuel ('hostlist.txt' içindeki domainler)",
            ["Filter_Off"] = "Kapalı (Tüm internet trafiğine uygula)",

            ["Rules_Title"] = "Paket Kuralları & Strateji",
            ["Rules_Desc"] = "Türkiye'deki ISS'ler için test edilmiş hazır stratejileri veya özel desync parametrelerini seçin.",
            ["Rules_PresetTitle"] = "Hazır Strateji Profili",
            ["Rules_ActiveParams"] = "Aktif Parametreler:",
            ["Btn_SaveStrategy"] = "Stratejiyi Kaydet",

            ["Filters_Title"] = "Filtreler & Domain Listeleri",
            ["Filters_Desc"] = "Bypass uygulanacak ve hariç tutulacak alan adlarını düzenleyin.",
            ["Filters_Hostlist"] = "DPI Uygulanacak Domainler",
            ["Filters_Excludelist"] = "Hariç Tutulacak Domainler",
            ["Btn_SaveHostlist"] = "Listeyi Kaydet",
            ["Btn_SaveExcludelist"] = "Hariç Listesini Kaydet",

            ["Dns_Title"] = "DNS Yapılandırması & Güvenlik",
            ["Dns_Desc"] = "DNS zehirlenmesini tespit edin, Google DoH veya DNSCrypt-proxy ile şifreleyin.",
            ["Dns_PoisonCheckTitle"] = "DNS Zehirlenmesi Kontrolü",
            ["Dns_PoisonCheckDesc"] = "ISS'nin Discord ve engelli sitelerin IP adreslerini sahte yönlendirmelere yönlendirip yönlendirmediğini test eder.",
            ["Btn_TestDns"] = "DNS Zehirlenmesini Şimdi Test Et",
            ["Dns_QuickSwitcher"] = "Hızlı DNS Değiştirici",
            ["Btn_GoogleDns"] = "Google DNS (8.8.8.8 / 8.8.4.4) [Önerilen]",
            ["Btn_AdguardDns"] = "AdGuard DNS (94.140.14.14 / 94.140.15.15)",
            ["Btn_CloudflareDns"] = "Cloudflare (1.1.1.1 / 1.0.0.1)",
            ["Btn_ResetDhcp"] = "Otomatiğe Al (DHCP Sıfırla)",

            ["Lan_Title"] = "Ağdaki Cihazlarla Paylaş (LAN)",
            ["Lan_Desc"] = "PlayStation, Xbox, Akıllı TV gibi cihazların Zapret üzerinden DPI aşımı yapmasını sağlayın.",
            ["Lan_RouterTitle"] = "go-pcap2socks Yönlendirici",
            ["Lan_RouterDesc"] = "Npcap paket yakalama sürücüsü ile yerel ağ trafiğini otomatik olarak Zapret'e yönlendirir.",
            ["Btn_StartLan"] = "LAN Paylaşımını Başlat",
            ["Btn_StopLan"] = "LAN Paylaşımını Durdur",

            ["Analysis_Title"] = "ISS Blok Analizi (Blockcheck2)",
            ["Analysis_Desc"] = "İnternet Servis Sağlayıcınızın uyguladığı DPI sansür tipini otomatik olarak tarayın.",
            ["Analysis_CardTitle"] = "Otomatik DPI Analiz Testi",
            ["Analysis_CardDesc"] = "Analiz işlemi 5-10 dakika sürebilir. Test tamamlandığında çalışan strateji otomatik kaydedilir.",
            ["Btn_StartAnalysis"] = "ISS Analizini Başlat",
            ["Btn_StopAnalysis"] = "Analizi Durdur",
            ["Analysis_ScanMode"] = "Tarama Modu:",
            ["Analysis_ScanFast"] = "Hızlı (İlk çalışanda dur)",
            ["Analysis_ScanSmart"] = "SmartScan (10 adet bul)",
            ["Analysis_ScanDeep"] = "Derin (Tamamı)",
            ["Analysis_StatusReady"] = "Hazır.",
            ["Analysis_StatusPreparing"] = "Hazırlanıyor (Servisler durduruluyor)...",
            ["Analysis_StatusRunning"] = "İşlem yapılıyor...",
            ["Analysis_StatusStopping"] = "Durduruluyor...",
            ["Analysis_StatusStopped"] = "Durduruldu.",
            ["Analysis_StatusCompleted"] = "Tamamlandı.",

            ["Recovery_Title"] = "Kurtarma & Sistem Temizliği",
            ["Recovery_Desc"] = "Sistemdeki tüm DPI servislerini, WinDivert sürücülerini kaldırın ve DNS ayarlarını fabrika ayarlarına döndürün.",
            ["Recovery_ResetTitle"] = "Tam Sistem Sıfırlama & Temizlik",
            ["Recovery_ListHeader"] = "Aşağıdaki işlemler yapılarak sistem fabrika ayarlarına döndürülür:",
            ["Recovery_Item1"] = "ZapretService ve dnscrypt-proxy arka plan servislerini durdurur ve siler.",
            ["Recovery_Item2"] = "WinDivert ve Monkey paket yönlendirme sürücülerini sistemden kaldırır.",
            ["Recovery_Item3"] = "Tüm ağ bağdaştırıcı DNS ayarlarını otomatiğe (DHCP) çeker.",
            ["Recovery_Item4"] = "Windows DNS çözümleyici önbelleğini (flushdns) temizler.",
            ["Btn_FullCleanup"] = "Tüm Kalıntıları ve Servisleri Temizle",

            ["Dialog_Success"] = "Başarılı",
            ["Dialog_Warning"] = "Uyarı",
            ["Dialog_Error"] = "Hata",
            ["Dialog_Info"] = "Bilgi",
            ["Dialog_Ok"] = "Tamam",
            ["Dialog_Cancel"] = "İptal",
            ["Dialog_Yes"] = "Evet",
            ["Dialog_No"] = "Hayır",

            ["Preset_Custom"] = "Analiz Sonucu (Özel Dosya)",
            ["Preset_ManualCustom"] = "Özel Strateji (Manuel Giriş)",
            ["Preset_DualProfile"] = "Türkiye Çift Profil (Discord + Web/Roblox)",
            ["Preset_TurkTelekom"] = "Türk Telekom",
            ["Preset_TTAlt"] = "TT Alternatif",
            ["Preset_Superonline"] = "Superonline",
            ["Preset_SOLAlt"] = "SOL Alternatif",
            ["Preset_TurkcellMobil"] = "Turkcell Mobil",
            ["Preset_Vodafone"] = "Vodafone",
            ["Preset_VodafoneMobil"] = "Vodafone Mobil",
            ["Preset_TelekomMobil"] = "Telekom Mobil",

            ["Msg_ConfigLoaded"] = "Ayar dosyası başarıyla yüklendi.",
            ["ProfileSave_Title"] = "Strateji Profilini Kaydet",
            ["ProfileSave_Header"] = "Bulunan Stratejiler",
            ["ProfileSave_Desc"] = "Tarama sonucunda aşağıdaki çalışan yapılandırmalar bulundu. Lütfen kaydetmek istediğinizi seçip bir isim verin.",
            ["ProfileSave_NameLabel"] = "Profil İsmi:",
            ["Btn_Save"] = "Kaydet",
            ["Msg_SelectStrategy"] = "Lütfen bir strateji seçin.",
            ["Msg_EnterProfileName"] = "Lütfen profil için bir isim girin.",
            ["Msg_ProfileNameEmpty"] = "Lütfen geçerli bir profil ismi girin.",
            ["Msg_ProfileSaved"] = "Profil başarıyla kaydedildi ve aktif hale getirildi.",
            ["Msg_ProfileDeleted"] = "Profil başarıyla silindi.",
            ["Msg_ProfileDeleteTitle"] = "Profili Sil",
            ["Msg_ProfileDeleteConfirm"] = "'{0}' profilini silmek istediğinize emin misiniz?",
            ["Msg_SaveStrategyTitle"] = "Stratejiyi Kaydet",
            ["Msg_SaveStrategyPrompt"] = "Bu strateji için bir profil ismi girin:",
            ["Msg_DefaultsRestoredTitle"] = "Varsayılanları Geri Yükle",
            ["Msg_DefaultsRestoredConfirm"] = "Silinen varsayılan profilleri geri yüklemek istediğinize emin misiniz?",
            ["Msg_DefaultsRestoredSuccess"] = "Varsayılan profiller başarıyla geri yüklendi.",
            ["Btn_RestoreDefaults"] = "Varsayılanlar",
            ["Log_FoundStrategies"] = "BULUNAN STRATEJİLER:",

            ["Msg_StrategySaved"] = "Strateji başarıyla kaydedildi!",
            ["Msg_HostlistSaved"] = "Hostlist kaydedildi.",
            ["Msg_ExcludelistSaved"] = "Hariç listesi kaydedildi.",
            ["Msg_ZapretCrash"] = "Zapret işlemi beklenmedik şekilde kapandı veya çöktü.",
            ["Msg_ZapretStartFail"] = "Zapret motoru başlatılamadı veya anında çöktü.\r\nLütfen dosya yollarını ve Anti-Cheat ayarlarını kontrol edin.",
            ["Msg_DnscryptConflict"] = "DNSCrypt servisi şu anda aktif. Özel bir DNS ayarlarsanız, DNSCrypt devre dışı bırakılacaktır. Devam etmek istiyor musunuz?",
            ["Msg_ServiceRemoved"] = "ZapretService başarıyla durduruldu ve kaldırıldı.",
            ["Msg_ServiceInstalled"] = "ZapretService Windows başlangıcında otomatik çalışacak şekilde kuruldu ve başarıyla başlatıldı!",
            ["Msg_ServiceStartFail"] = "Servis kaydedildi fakat başlatılamadı. Sistemde başka bir WinDivert oturumu, Anti-Cheat engeli olabilir veya bilgisayarı yeniden başlatmanız gerekebilir.",
            ["Msg_ConflictDetected"] = "Arka planda kilitli veya kapatılamayan işlemler (winws2) tespit edildi. Sistemin yeniden başlatılması gerekiyor.\n\nŞimdi yeniden başlatmak ister misiniz?",
            ["Msg_DnscryptRemoved"] = "DNSCrypt kaldırıldı ve DNS otomatiğe (DHCP) alındı.",
            ["Msg_DnscryptInstalled"] = "DNSCrypt servisi kuruldu ve sistem DNS adresi 127.0.0.1 olarak ayarlandı.",
            ["Msg_DnscryptFail"] = "DNSCrypt kurulumu başarısız oldu.",
            ["Msg_DnscryptServerChanged"] = "DNSCrypt sunucusu değiştirildi ve servis yeniden başlatıldı.",
            ["Msg_DnsGoogleSet"] = "Sistem DNS adresi Google DNS (8.8.8.8 / 8.8.4.4) olarak ayarlandı ve önbellek temizlendi.",
            ["Msg_DnsAdguardSet"] = "Sistem DNS adresi AdGuard DNS (94.140.14.14 / 94.140.15.15) olarak ayarlandı ve önbellek temizlendi.",
            ["Msg_DnsCloudflareSet"] = "Sistem DNS adresi Cloudflare (1.1.1.1 / 1.0.0.1) olarak ayarlandı ve önbellek temizlendi.",
            ["Msg_DnsQuad9Set"] = "Sistem DNS adresi Quad9 (9.9.9.9 / 149.112.112.112) olarak ayarlandı ve önbellek temizlendi.",
            ["Msg_DnsDhcpSet"] = "Sistem DNS ayarları otomatiğe (DHCP) alındı.",
            ["Msg_NpcapNotFound"] = "Sistemde Npcap paket yakalama sürücüsü bulunamadı.\r\n\r\nAğ Paylaşımı (LAN) ile konsol ve TV gibi cihazların Zapret üzerinden DPI aşımı yapması için Npcap gereklidir.\r\n\r\nNpcap indirme sayfası açılsın mı?",
            ["Msg_FirewallPrompt"] = "go-pcap2socks için Windows Güvenlik Duvarı izni gerekiyor.\r\nGelen uyarıda Erişime İzin Ver'e basın.",
            ["Msg_AnalysisDoneWorking"] = "Analiz tamamlandı!\r\n\r\nÇalışan Strateji:\r\n{0}",
            ["Msg_AnalysisDoneTimeout"] = "Analiz tamamlandı. Çalışan bir DPI bypass stratejisi bulunamadı.",
            ["Msg_NoStrategiesFound"] = "Analiz tamamlandı. Çalışan bir DPI bypass stratejisi bulunamadı.",
            ["Msg_AnalysisTimeout"] = "Analiz süresi zaman aşımına uğradı (12 dakika aşıldı).",
            ["Msg_DnsPoisonFound"] = "ISS tarafından DNS Zehirlenmesi saptandı!\r\n\r\nSistem DNS adresiniz Google DNS (8.8.8.8 / 8.8.4.4) olarak ayarlansın mı?",
            ["Title_DnsThreat"] = "DNS Tehdidi Saptandı",
            ["Title_DnsReport"] = "DNS Tanılama Raporu",
            ["Title_CleanupDone"] = "Temizlik Tamamlandı",
            ["Title_Firewall"] = "Güvenlik Duvarı",
            ["Title_CrashWarning"] = "Zapret Çökme Uyarısı",

            ["Btn_Ok"] = "Tamam",
            ["Btn_Cancel"] = "İptal",
            ["Btn_Yes"] = "Evet",
            ["Btn_No"] = "Hayır",
            ["Dialog_UpdateAvailableTitle"] = "Yeni Güncelleme Mevcut! 🚀",
            ["Dialog_UpdateFoundPrompt"] = "ZapretDPI-TR {0} sürümü yayınlandı!\r\nŞu anki sürümünüz: {1}\r\n\r\nŞimdi güncellemek istiyor musunuz?",
            ["Dialog_UpToDateTitle"] = "Yazılım Güncel",
            ["Dialog_UpToDateText"] = "En son sürümü ({0}) kullanıyorsunuz. Yeni bir güncelleme bulunamadı.",
            ["Dialog_UpdateCheckFailed"] = "Güncellemeler denetlenirken bir hata oluştu veya GitHub'a ulaşılamadı.",
            ["Dialog_UpdateTitle"] = "Güncelleme",
            ["Dialog_ReleaseNotesTitle"] = "Sürüm Notları & Değişiklikler",
            ["Dialog_BtnUpdateNow"] = "Şimdi Güncelle ve Yeniden Başlat",
            ["Dialog_BtnLater"] = "Daha Sonra",
            ["Dialog_DownloadingUpdate"] = "Güncelleme indiriliyor...",
            ["Dialog_ApplyingUpdate"] = "Güncelleme uygulanıyor...",
            ["Dns_CleanTag"] = "Temiz",
            ["Dns_PoisonedTag"] = "ZEHİRLENMİŞ IP!",
            ["Dns_UnresolvedTag"] = "Çözümlenemedi",
            ["Dns_CleanSummary"] = "DNS sorguları tamamen temiz ve gerçek sunuculara yönlendiriliyor. ({0}/{1} başarılı)",
            ["Dns_PoisonedSummary"] = "ISS tarafından DNS Zehirlenmesi saptandı! Engelli siteler sahte IP adreslerine yönlendiriliyor.",
            ["Dns_TotalResponseTime"] = "Toplam Yanıt Süresi: {0} ms",
            ["Dns_DomainAnalysisDetails"] = "Alan Adı Analiz Detayları",

            ["Status_Starting"] = "⏳ Başlatılıyor...",
            ["Status_Stopping"] = "⏳ Durduruluyor...",
            ["Status_Installing"] = "⏳ Kuruluyor...",
            ["Status_Removing"] = "⏳ Kaldırılıyor...",
            ["Status_Cleaning"] = "⏳ Temizleniyor...",
            ["Status_Applying"] = "⏳ Uygulanıyor...",
            ["Status_Testing"] = "⏳ Test ediliyor...",
            ["Btn_TestPoison"] = "DNS Zehirlenmesini Şimdi Test Et",

            ["ProfileSave_ApplyNow"] = "Bu stratejiyi varsayılan yap ve hemen Zapret'i başlat",
            ["Btn_SaveAndApply"] = "Kaydet ve Etkinleştir",
            ["Overview_ActiveProfileTitle"] = "Kullanılacak DPI Profili",
            ["Overview_ActiveProfileDesc"] = "Standart başlatma ve Windows Servisi bu seçili stratejiyle çalışır.",

            ["About_Title"] = "Hakkında",
            ["About_Subtitle"] = "ZapretDPI-TR sürüm bilgileri, sistem ayrıntıları ve lisanslar.",
            ["About_Description"] = "Windows üzerindeki ağ yönlendirme, DPI yöntemleri (Zapret2 LUA), DNS güvenliği ve otomatik ISS blok analizini tek yerden yöneten modern ve kompakt bir DPI aşım aracıdır.",
            ["About_PlatformCardTitle"] = "Platform & Sistem",
            ["About_Platform"] = "Platform:",
            ["About_Arch"] = "Mimari:",
            ["About_Runtime"] = "Çalışma Zamanı:",
            ["About_Language"] = "Arayüz Dili:",
            ["About_DpiCardTitle"] = "DPI Çekirdeği & Ağ",
            ["About_Core"] = "DPI Çekirdeği:",
            ["About_Driver"] = "Paket Sürücüsü:",
            ["About_Dns"] = "Şifreli DNS:",
            ["About_Lan"] = "Ağ Paylaşımı:",
            ["About_LicenseTitle"] = "Lisans & Açık Kaynak Bildirimi",
            ["About_License"] = "ZapretDPI-TR açık kaynaklı bir yazılımdır ve MIT Lisansı altında dağıtılmaktadır. Proje; Zapret2 (WinWS2), WinDivert, dnscrypt-proxy ve go-pcap2socks açık kaynaklı bileşenlerinden güç alır. Tüm üçüncü taraf kütüphane ve sürücülerin telif hakları kendi bağımsız geliştiricilerine aittir.",
            ["About_BtnRepo"] = "Proje Deposu (GitHub)",
            ["Btn_CheckUpdates"] = "Güncellemeleri Denetle"
        },

        ["en"] = new()
        {
            ["App_Title"] = "ZapretDPI-TR",
            ["Nav_Overview"] = "Overview",
            ["Nav_Engine"] = "DPI Routing",
            ["Nav_Rules"] = "Packet Rules",
            ["Nav_Filters"] = "Filters & Domains",
            ["Nav_Dns"] = "DNS & DoH",
            ["Nav_Lan"] = "LAN Sharing",
            ["Nav_Analysis"] = "ISP Analysis",
            ["Nav_Console"] = "Console & Logs",
            ["Nav_Recovery"] = "Recovery",
            ["Nav_About"] = "About",
            ["Footer_Core"] = "DPI Core",
            ["Footer_Version"] = "Software Version",

            ["Overview_Title"] = "Overview",
            ["Overview_ReadySubtitle"] = "ZapretDPI-TR ready • Ready to start",
            ["Overview_ServiceSubtitle"] = "ZapretService active • Network protection on",
            ["Overview_ProcessSubtitle"] = "Zapret process running • Traffic routed",
            ["Overview_StoppingSubtitle"] = "Stopping...",
            ["Overview_StartingSubtitle"] = "Starting...",

            ["Pill_Routing"] = "Active Routing",
            ["Pill_Engine"] = "DPI Method",
            ["Pill_Service"] = "Running Service",
            ["Pill_Dns"] = "DNS / DoH",
            ["Pill_WinDivert"] = "WinDivert Driver",
            ["Pill_Lan"] = "LAN Sharing",

            ["Status_NotInstalled"] = "Not Installed",
            ["Status_ServiceActive"] = "Service Active",
            ["Status_ManualActive"] = "Manual Active",
            ["Status_Installed"] = "Installed (v1.0.4)",
            ["Status_Active"] = "Active",
            ["Status_Off"] = "Off",
            ["Status_ZeroService"] = "0 services",
            ["Status_OneProcess"] = "1 process",
            ["Status_MultipleServices"] = "{0} Services (Zapret + DNS)",
            ["Status_OneServiceZapret"] = "1 Service (ZapretService)",
            ["Status_OneServiceDnscrypt"] = "1 Service (DNSCrypt)",
            ["Status_StandardDoh"] = "Standard / DoH",
            ["Status_DnscryptActive"] = "DNSCrypt (127.0.0.1)",

            ["Action_SectionTitle"] = "Routing & Installation",
            ["Action_SectionDesc"] = "Manage Windows routing and DPI bypass components.",

            ["Action_QuickStartTitle"] = "Standard Start",
            ["Action_QuickStartDesc"] = "Recommended. Launches dual-profile (Discord + Web) DPI bypass.",
            ["Btn_StartZapret"] = "Start Zapret",
            ["Btn_StopZapret"] = "Stop Zapret",

            ["Action_ServiceTitle"] = "Windows Service (Auto-Start)",
            ["Action_ServiceDesc"] = "Runs quietly in background automatically on Windows startup.",
            ["Btn_InstallService"] = "Install as Service",
            ["Btn_RemoveService"] = "Remove Service",

            ["Action_DnscryptTitle"] = "Encrypted DNS (DNSCrypt-proxy)",
            ["Action_DnscryptDesc"] = "Protects against ISP DNS poisoning with encrypted DNS.",
            ["Btn_InstallDnscrypt"] = "Install DNSCrypt",
            ["Btn_RemoveDnscrypt"] = "Remove DNSCrypt",

            ["Dns_DnscryptTitle"] = "Encrypted DNS Server (DNSCrypt)",
            ["Dns_DnscryptDesc"] = "Select the encrypted DNS server to use when DNSCrypt is active.",
            ["Console_Title"] = "Live Console (Log Stream)",
            ["Console_Desc"] = "Monitor the latest events from the Zapret service and engine here.",
            ["Console_BtnClear"] = "Clear Logs",
            ["Console_BtnOpenDir"] = "Open Log Folder",

            ["Engine_Title"] = "DPI Routing & Engine",
            ["Engine_Desc"] = "Configure engine core and traffic filtering rules.",
            ["Engine_Selection"] = "Engine Core Selection",
            ["Engine_Zapret2"] = "Zapret2 v1.0.4 (New LUA Engine - Recommended)",
            ["Engine_Zapret2Desc"] = "Advanced LUA desync modules with dual-profile (Discord + web) support.",

            ["Engine_FilterMode"] = "Filter Mode",
            ["Filter_Auto"] = "Auto (Zapret dynamically generates autohostlist)",
            ["Filter_Manual"] = "Manual (Only domains in 'hostlist.txt')",
            ["Filter_Off"] = "Off (Apply to all internet traffic)",

            ["Rules_Title"] = "Packet Rules & Strategy",
            ["Rules_Desc"] = "Select ISP tested presets or customize desync arguments.",
            ["Rules_PresetTitle"] = "Preset Strategy Profile",
            ["Rules_ActiveParams"] = "Active Parameters:",
            ["Btn_SaveStrategy"] = "Save Strategy",

            ["Filters_Title"] = "Filters & Domain Lists",
            ["Filters_Desc"] = "Configure target domains to bypass and excluded domain names.",
            ["Filters_Hostlist"] = "Target Domains for DPI",
            ["Filters_Excludelist"] = "Excluded Domains",
            ["Btn_SaveHostlist"] = "Save Domain List",
            ["Btn_SaveExcludelist"] = "Save Exclude List",

            ["Dns_Title"] = "DNS Configuration & Security",
            ["Dns_Desc"] = "Detect ISP DNS poisoning, secure with Google DoH or DNSCrypt.",
            ["Dns_PoisonCheckTitle"] = "DNS Poisoning Check",
            ["Dns_PoisonCheckDesc"] = "Tests if ISP redirects Discord and blocked domains to fake IP addresses.",
            ["Btn_TestDns"] = "Test DNS Poisoning Now",
            ["Dns_QuickSwitcher"] = "Quick DNS Switcher",
            ["Btn_GoogleDns"] = "Google DNS (8.8.8.8 / 8.8.4.4) [Recommended]",
            ["Btn_AdguardDns"] = "AdGuard DNS (94.140.14.14 / 94.140.15.15)",
            ["Btn_CloudflareDns"] = "Cloudflare (1.1.1.1 / 1.0.0.1)",
            ["Btn_ResetDhcp"] = "Reset to DHCP (Automatic)",

            ["Lan_Title"] = "Share with LAN Devices",
            ["Lan_Desc"] = "Allow PlayStation, Xbox, Smart TV and other LAN devices to bypass DPI.",
            ["Lan_RouterTitle"] = "go-pcap2socks Router",
            ["Lan_RouterDesc"] = "Automatically routes LAN traffic to Zapret using Npcap driver.",
            ["Btn_StartLan"] = "Start LAN Sharing",
            ["Btn_StopLan"] = "Stop LAN Sharing",

            ["Analysis_Title"] = "ISP Block Analysis (Blockcheck2)",
            ["Analysis_Desc"] = "Automatically scan and detect your ISP's DPI censorship characteristics.",
            ["Analysis_CardTitle"] = "Automated DPI Analysis Test",
            ["Analysis_CardDesc"] = "Analysis may take 5-10 minutes. Working strategy is automatically saved when complete.",
            ["Btn_StartAnalysis"] = "Start ISP Analysis",
            ["Btn_StopAnalysis"] = "Stop Analysis",
            ["Analysis_ScanMode"] = "Scan Mode:",
            ["Analysis_ScanFast"] = "Fast (Stop on first success)",
            ["Analysis_ScanSmart"] = "SmartScan (Find 10)",
            ["Analysis_ScanDeep"] = "Deep (All)",
            ["Analysis_StatusReady"] = "Ready.",
            ["Analysis_StatusPreparing"] = "Preparing (Stopping services)...",
            ["Analysis_StatusRunning"] = "In progress...",
            ["Analysis_StatusStopping"] = "Stopping...",
            ["Analysis_StatusStopped"] = "Stopped.",
            ["Analysis_StatusCompleted"] = "Completed.",

            ["Recovery_Title"] = "Recovery & System Cleanup",
            ["Recovery_Desc"] = "Remove all DPI services, WinDivert drivers and reset network DNS to defaults.",
            ["Recovery_ResetTitle"] = "Full System Reset & Cleanup",
            ["Recovery_ListHeader"] = "The following actions will be performed to restore the system to defaults:",
            ["Recovery_Item1"] = "Stops and removes ZapretService and dnscrypt-proxy background services.",
            ["Recovery_Item2"] = "Uninstalls WinDivert and packet redirection drivers from the system.",
            ["Recovery_Item3"] = "Resets all network adapter DNS settings to automatic (DHCP).",
            ["Recovery_Item4"] = "Clears and flushes the Windows DNS resolver cache (flushdns).",
            ["Btn_FullCleanup"] = "Clean All Services & Drivers",

            ["Dialog_Success"] = "Success",
            ["Dialog_Warning"] = "Warning",
            ["Dialog_Error"] = "Error",
            ["Dialog_Info"] = "Info",
            ["Dialog_Ok"] = "OK",
            ["Dialog_Cancel"] = "Cancel",
            ["Dialog_Yes"] = "Yes",
            ["Dialog_No"] = "No",

            ["Preset_Custom"] = "Analysis Result (Custom File)",
            ["Preset_ManualCustom"] = "Custom Strategy (Manual Input)",
            ["Preset_DualProfile"] = "Turkey Dual Profile (Discord + Web/Roblox)",
            ["Preset_TurkTelekom"] = "Turk Telekom",
            ["Preset_TTAlt"] = "TT Alternative",
            ["Preset_Superonline"] = "Superonline",
            ["Preset_SOLAlt"] = "SOL Alternative",
            ["Preset_TurkcellMobil"] = "Turkcell Mobile",
            ["Preset_Vodafone"] = "Vodafone",
            ["Preset_VodafoneMobil"] = "Vodafone Mobile",
            ["Preset_TelekomMobil"] = "Telekom Mobile",

            ["Msg_ConfigLoaded"] = "Config loaded successfully.",
            ["ProfileSave_Title"] = "Save Strategy Profile",
            ["ProfileSave_Header"] = "Identified Strategies",
            ["ProfileSave_Desc"] = "The following working configurations were found. Please select one and enter a profile name.",
            ["ProfileSave_NameLabel"] = "Profile Name:",
            ["Btn_Save"] = "Save",
            ["Msg_SelectStrategy"] = "Please select a strategy from the list to save.",
            ["Msg_EnterProfileName"] = "Please enter a profile name.",
            ["Msg_ProfileNameEmpty"] = "Please enter a valid profile name.",
            ["Msg_ProfileSaved"] = "Strategy profile was saved and activated successfully!",
            ["Msg_ProfileDeleted"] = "Profile deleted successfully.",
            ["Msg_ProfileDeleteTitle"] = "Delete Profile",
            ["Msg_ProfileDeleteConfirm"] = "Are you sure you want to delete the profile '{0}'?",
            ["Msg_SaveStrategyTitle"] = "Save Strategy",
            ["Msg_SaveStrategyPrompt"] = "Enter a profile name for this strategy:",
            ["Msg_DefaultsRestoredTitle"] = "Restore Defaults",
            ["Msg_DefaultsRestoredConfirm"] = "Are you sure you want to restore the deleted default profiles?",
            ["Msg_DefaultsRestoredSuccess"] = "Default profiles have been restored successfully.",
            ["Btn_RestoreDefaults"] = "Defaults",
            ["Log_FoundStrategies"] = "IDENTIFIED STRATEGIES:",

            ["Msg_StrategySaved"] = "Strategy saved successfully!",
            ["Msg_HostlistSaved"] = "Hostlist saved.",
            ["Msg_ExcludelistSaved"] = "Exclude list saved.",
            ["Msg_ZapretCrash"] = "Zapret process closed unexpectedly or crashed.",
            ["Msg_ZapretStartFail"] = "Zapret engine failed to start or crashed immediately.\r\nPlease check file paths and Anti-Cheat software.",
            ["Msg_DnscryptConflict"] = "DNSCrypt service is currently active. If you set a custom DNS, DNSCrypt will be bypassed. Do you want to continue?",
            ["Msg_ServiceRemoved"] = "ZapretService was stopped and uninstalled successfully.",
            ["Msg_ServiceInstalled"] = "ZapretService was installed and started successfully to run on Windows startup!",
            ["Msg_ServiceStartFail"] = "Service was registered but failed to start. Another WinDivert session may be open or computer reboot might be required.",
            ["Msg_ConflictDetected"] = "Locked or unkillable background processes (winws2) detected. System reboot is required.\n\nWould you like to restart your computer now?",
            ["Msg_DnscryptRemoved"] = "DNSCrypt removed and DNS reset to automatic (DHCP).",
            ["Msg_DnscryptInstalled"] = "DNSCrypt installed and system DNS configured to 127.0.0.1.",
            ["Msg_DnscryptFail"] = "DNSCrypt installation failed.",
            ["Msg_DnscryptServerChanged"] = "DNSCrypt server changed and service restarted.",
            ["Msg_DnsGoogleSet"] = "System DNS set to Google DNS (8.8.8.8 / 8.8.4.4) and cache flushed.",
            ["Msg_DnsAdguardSet"] = "System DNS set to AdGuard DNS (94.140.14.14 / 94.140.15.15) and cache flushed.",
            ["Msg_DnsCloudflareSet"] = "System DNS set to Cloudflare (1.1.1.1 / 1.0.0.1) and cache flushed.",
            ["Msg_DnsQuad9Set"] = "System DNS set to Quad9 (9.9.9.9 / 149.112.112.112) and cache flushed.",
            ["Msg_DnsDhcpSet"] = "System DNS reset to automatic (DHCP).",
            ["Msg_NpcapNotFound"] = "Npcap driver not found.\r\n\r\nNpcap is required for LAN sharing to forward traffic for consoles and Smart TVs.\r\n\r\nOpen Npcap download page?",
            ["Msg_FirewallPrompt"] = "Windows Firewall permission required for go-pcap2socks.\r\nPlease click Allow Access when prompted.",
            ["Msg_AnalysisDoneWorking"] = "Analysis complete!\r\n\r\nWorking Strategy:\r\n{0}",
            ["Msg_AnalysisDoneTimeout"] = "Analysis finished. No working DPI bypass strategy found.",
            ["Msg_NoStrategiesFound"] = "Analysis finished. No working DPI bypass strategy found.",
            ["Msg_AnalysisTimeout"] = "Analysis timed out (exceeded 12 minutes).",
            ["Msg_DnsPoisonFound"] = "DNS Poisoning detected from your ISP!\r\n\r\nWould you like to switch to Google DNS (8.8.8.8 / 8.8.4.4)?",
            ["Title_DnsThreat"] = "DNS Threat Detected",
            ["Title_DnsReport"] = "DNS Diagnostic Report",
            ["Title_CleanupDone"] = "Cleanup Completed",
            ["Title_Firewall"] = "Firewall",
            ["Title_CrashWarning"] = "Zapret Crash Warning",

            ["Btn_Ok"] = "OK",
            ["Btn_Cancel"] = "Cancel",
            ["Btn_Yes"] = "Yes",
            ["Btn_No"] = "No",
            ["Dialog_UpdateAvailableTitle"] = "New Update Available! 🚀",
            ["Dialog_UpdateFoundPrompt"] = "ZapretDPI-TR {0} is available!\r\nCurrent version: {1}\r\n\r\nWould you like to update now?",
            ["Dialog_UpToDateTitle"] = "Up to Date",
            ["Dialog_UpToDateText"] = "You are using the latest version ({0}). No updates available.",
            ["Dialog_UpdateCheckFailed"] = "Failed to check for updates or GitHub is unreachable.",
            ["Dialog_UpdateTitle"] = "Update",
            ["Dialog_ReleaseNotesTitle"] = "Release Notes & Changes",
            ["Dialog_BtnUpdateNow"] = "Update Now & Restart",
            ["Dialog_BtnLater"] = "Later",
            ["Dialog_DownloadingUpdate"] = "Downloading update...",
            ["Dialog_ApplyingUpdate"] = "Applying update...",
            ["Dns_CleanTag"] = "Clean",
            ["Dns_PoisonedTag"] = "POISONED IP!",
            ["Dns_UnresolvedTag"] = "Unresolved",
            ["Dns_CleanSummary"] = "DNS queries are clean and routed to authentic servers. ({0}/{1} successful)",
            ["Dns_PoisonedSummary"] = "ISP DNS poisoning detected! Blocked sites are redirected to fake IP addresses.",
            ["Dns_TotalResponseTime"] = "Total Response Time: {0} ms",
            ["Dns_DomainAnalysisDetails"] = "Domain Analysis Details",

            ["Status_Starting"] = "⏳ Starting...",
            ["Status_Stopping"] = "⏳ Stopping...",
            ["Status_Installing"] = "⏳ Installing...",
            ["Status_Removing"] = "⏳ Removing...",
            ["Status_Cleaning"] = "⏳ Cleaning...",
            ["Status_Applying"] = "⏳ Applying...",
            ["Status_Testing"] = "⏳ Testing...",
            ["Btn_TestPoison"] = "Test DNS Poisoning Now",

            ["ProfileSave_ApplyNow"] = "Set as default profile and start Zapret immediately",
            ["Btn_SaveAndApply"] = "Save & Activate",
            ["Overview_ActiveProfileTitle"] = "Active DPI Profile",
            ["Overview_ActiveProfileDesc"] = "Active strategy used by both quick start and Windows service.",

            ["About_Title"] = "About",
            ["About_Subtitle"] = "ZapretDPI-TR version information, system details and licenses.",
            ["About_Description"] = "A modern and compact DPI bypass and network routing management tool for Windows, Zapret2 LUA engine, DNS security, and automated ISP analysis.",
            ["About_PlatformCardTitle"] = "Platform & System",
            ["About_Platform"] = "Platform:",
            ["About_Arch"] = "Architecture:",
            ["About_Runtime"] = "Runtime:",
            ["About_Language"] = "UI Language:",
            ["About_DpiCardTitle"] = "DPI Core & Networking",
            ["About_Core"] = "DPI Core:",
            ["About_Driver"] = "Packet Driver:",
            ["About_Dns"] = "Encrypted DNS:",
            ["About_Lan"] = "LAN Sharing:",
            ["About_LicenseTitle"] = "License & Open Source Notice",
            ["About_License"] = "ZapretDPI-TR is open-source software distributed under the MIT License. It is powered by open-source core components including Zapret2 (WinWS2), WinDivert, dnscrypt-proxy, and go-pcap2socks. Copyrights and trademarks belong to their respective authors.",
            ["About_BtnRepo"] = "Project Repository (GitHub)",
            ["Btn_CheckUpdates"] = "Check for Updates"
        },

        ["ru"] = new()
        {
            ["App_Title"] = "ZapretDPI-TR",
            ["Nav_Overview"] = "Обзор",
            ["Nav_Engine"] = "Маршрутизация DPI",
            ["Nav_Rules"] = "Правила пакетов",
            ["Nav_Filters"] = "Фильтры и домены",
            ["Nav_Dns"] = "DNS и DoH",
            ["Nav_Lan"] = "Раздача по сети (LAN)",
            ["Nav_Analysis"] = "Анализ провайдера",
            ["Nav_Console"] = "Консоль и Журнал",
            ["Nav_Recovery"] = "Восстановление",
            ["Nav_About"] = "О программе",
            ["Footer_Core"] = "Ядро DPI",
            ["Footer_Version"] = "Версия программы",

            ["Overview_Title"] = "Обзор",
            ["Overview_ReadySubtitle"] = "ZapretDPI-TR готов • Готов к запуску",
            ["Overview_ServiceSubtitle"] = "Служба ZapretService активна • Защита сети включена",
            ["Overview_ProcessSubtitle"] = "Процесс Zapret запущен • Трафик перенаправляется",
            ["Overview_StoppingSubtitle"] = "Остановка...",
            ["Overview_StartingSubtitle"] = "Запуск...",

            ["Pill_Routing"] = "Маршрутизация",
            ["Pill_Engine"] = "Метод DPI",
            ["Pill_Service"] = "Служба Windows",
            ["Pill_Dns"] = "DNS / DoH",
            ["Pill_WinDivert"] = "Драйвер WinDivert",
            ["Pill_Lan"] = "Раздача (LAN)",

            ["Status_NotInstalled"] = "Не установлено",
            ["Status_ServiceActive"] = "Служба активна",
            ["Status_ManualActive"] = "Вручную активен",
            ["Status_Installed"] = "Установлено (v1.0.4)",
            ["Status_Active"] = "Активно",
            ["Status_Off"] = "Выключено",
            ["Status_ZeroService"] = "0 служб",
            ["Status_OneProcess"] = "1 процесс",
            ["Status_MultipleServices"] = "{0} Службы (Zapret + DNS)",
            ["Status_OneServiceZapret"] = "1 Служба (ZapretService)",
            ["Status_OneServiceDnscrypt"] = "1 Служба (DNSCrypt)",
            ["Status_StandardDoh"] = "Стандартный / DoH",
            ["Status_DnscryptActive"] = "DNSCrypt (127.0.0.1)",

            ["Action_SectionTitle"] = "Настройка маршрутизации",
            ["Action_SectionDesc"] = "Управление компонентами маршрутизации Windows и обхода DPI.",

            ["Action_QuickStartTitle"] = "Стандартный запуск",
            ["Action_QuickStartDesc"] = "Рекомендуется. Запуск двухпрофильного обхода DPI (Discord + Web).",
            ["Btn_StartZapret"] = "Запустить Zapret",
            ["Btn_StopZapret"] = "Остановить Zapret",

            ["Action_ServiceTitle"] = "Служба Windows (Автозапуск)",
            ["Action_ServiceDesc"] = "Автоматически работает в фоновом режиме при запуске Windows.",
            ["Btn_InstallService"] = "Установить службу",
            ["Btn_RemoveService"] = "Удалить службу",

            ["Action_DnscryptTitle"] = "Шифрованный DNS (DNSCrypt-proxy)",
            ["Action_DnscryptDesc"] = "Защита от DNS-спуфинга со стороны интернет-провайдера.",
            ["Btn_InstallDnscrypt"] = "Установить DNSCrypt",
            ["Btn_RemoveDnscrypt"] = "Удалить DNSCrypt",

            ["Dns_DnscryptTitle"] = "Шифрованный DNS-сервер (DNSCrypt)",
            ["Dns_DnscryptDesc"] = "Выберите зашифрованный DNS-сервер для использования при активном DNSCrypt.",
            ["Console_Title"] = "Живая консоль (Журнал)",
            ["Console_Desc"] = "Здесь вы можете отслеживать последние события от службы и ядра Zapret.",
            ["Console_BtnClear"] = "Очистить логи",
            ["Console_BtnOpenDir"] = "Открыть папку логов",

            ["Engine_Title"] = "Маршрутизация и движок DPI",
            ["Engine_Desc"] = "Настройка ядра движка и правил фильтрации пакетов.",
            ["Engine_Selection"] = "Выбор ядра DPI",
            ["Engine_Zapret2"] = "Zapret2 v1.0.4 (Новый LUA движок - Рекомендуется)",
            ["Engine_Zapret2Desc"] = "Новые модули фильтрации LUA с поддержкой двух профилей (Discord + web).",

            ["Engine_FilterMode"] = "Режим фильтрации",
            ["Filter_Auto"] = "Авто (Zapret динамически создает autohostlist)",
            ["Filter_Manual"] = "Вручную (Только домены из 'hostlist.txt')",
            ["Filter_Off"] = "Выключено (Применять ко всему трафику)",

            ["Rules_Title"] = "Правила пакетов и стратегии",
            ["Rules_Desc"] = "Готовые протестированные профили или пользовательские параметры desync.",
            ["Rules_PresetTitle"] = "Профиль готовой стратегии",
            ["Rules_ActiveParams"] = "Активные параметры:",
            ["Btn_SaveStrategy"] = "Сохранить стратегию",

            ["Filters_Title"] = "Фильтры и списки доменов",
            ["Filters_Desc"] = "Настройка целевых доменов для обхода и доменов-исключений.",
            ["Filters_Hostlist"] = "Целевые домены для DPI",
            ["Filters_Excludelist"] = "Исключенные домены",
            ["Btn_SaveHostlist"] = "Сохранить список",
            ["Btn_SaveExcludelist"] = "Сохранить исключения",

            ["Dns_Title"] = "Настройка DNS и безопасность",
            ["Dns_Desc"] = "Проверка DNS-спуфинга, шифрование через Google DoH или DNSCrypt.",
            ["Dns_PoisonCheckTitle"] = "Проверка DNS-спуфинга",
            ["Dns_PoisonCheckDesc"] = "Проверяет, перенаправляет ли провайдер запросы на поддельные IP-адреса.",
            ["Btn_TestDns"] = "Проверить DNS-спуфинг сейчас",
            ["Dns_QuickSwitcher"] = "Быстрое переключение DNS",
            ["Btn_GoogleDns"] = "Google DNS (8.8.8.8 / 8.8.4.4) [Рекомендуется]",
            ["Btn_AdguardDns"] = "AdGuard DNS (94.140.14.14 / 94.140.15.15)",
            ["Btn_CloudflareDns"] = "Cloudflare (1.1.1.1 / 1.0.0.1)",
            ["Btn_ResetDhcp"] = "Сброс на DHCP (Автоматически)",

            ["Lan_Title"] = "Раздача на устройства в сети (LAN)",
            ["Lan_Desc"] = "Позволяет приставкам PlayStation, Xbox, Smart TV обходить DPI через Zapret.",
            ["Lan_RouterTitle"] = "Маршрутизатор go-pcap2socks",
            ["Lan_RouterDesc"] = "Автоматически перенаправляет сетевой трафик в Zapret с помощью Npcap.",
            ["Btn_StartLan"] = "Запустить раздачу (LAN)",
            ["Btn_StopLan"] = "Остановить раздачу",

            ["Analysis_Title"] = "Анализ блокировок провайдера (Blockcheck2)",
            ["Analysis_Desc"] = "Автоматическое сканирование и определение методов DPI-цензуры вашего провайдера.",
            ["Analysis_CardTitle"] = "Автоматический тест анализа DPI",
            ["Analysis_CardDesc"] = "Анализ может занять 5-10 минут. Рабочая стратегия будет автоматически сохранена по завершении.",
            ["Btn_StartAnalysis"] = "Запустить анализ провайдера",
            ["Btn_StopAnalysis"] = "Остановить анализ",
            ["Analysis_ScanMode"] = "Режим сканирования:",
            ["Analysis_ScanFast"] = "Быстрый (Остановка на первом успехе)",
            ["Analysis_ScanSmart"] = "SmartScan (Найти 10)",
            ["Analysis_ScanDeep"] = "Глубокий (Все)",
            ["Analysis_StatusReady"] = "Готов.",
            ["Analysis_StatusPreparing"] = "Подготовка (Остановка служб)...",
            ["Analysis_StatusRunning"] = "Выполняется...",
            ["Analysis_StatusStopping"] = "Остановка...",
            ["Analysis_StatusStopped"] = "Остановлено.",
            ["Analysis_StatusCompleted"] = "Завершено.",

            ["Recovery_Title"] = "Восстановление и очистка системы",
            ["Recovery_Desc"] = "Удаление всех служб DPI, драйверов WinDivert и сброс настроек DNS до заводских.",
            ["Recovery_ResetTitle"] = "Полный сброс и очистка системы",
            ["Recovery_ListHeader"] = "Следующие действия будут выполнены для возврата к настройкам по умолчанию:",
            ["Recovery_Item1"] = "Останавливает и удаляет фоновые службы ZapretService и dnscrypt-proxy.",
            ["Recovery_Item2"] = "Удаляет из системы драйверы WinDivert и перенаправления пакетов.",
            ["Recovery_Item3"] = "Сбрасывает настройки DNS всех сетевых адаптеров на автоматические (DHCP).",
            ["Recovery_Item4"] = "Очищает кэш сопоставителя DNS Windows (flushdns).",
            ["Btn_FullCleanup"] = "Очистить все службы и остатки",

            ["Dialog_Success"] = "Успешно",
            ["Dialog_Warning"] = "Предупреждение",
            ["Dialog_Error"] = "Ошибка",
            ["Dialog_Info"] = "Информация",
            ["Dialog_Ok"] = "ОК",
            ["Dialog_Cancel"] = "Отмена",
            ["Dialog_Yes"] = "Да",
            ["Dialog_No"] = "Нет",

            ["Preset_Custom"] = "Результат анализа (Пользовательский)",
            ["Preset_DualProfile"] = "Турция двойной профиль (Discord + Web/Roblox)",
            ["Preset_TurkTelekom"] = "Turk Telekom",
            ["Preset_TTAlt"] = "TT Альтернатива",
            ["Preset_Superonline"] = "Superonline",
            ["Preset_SOLAlt"] = "SOL Альтернатива",
            ["Preset_TurkcellMobil"] = "Turkcell Мобильный",
            ["Preset_Vodafone"] = "Vodafone",
            ["Preset_VodafoneMobil"] = "Vodafone Мобильный",
            ["Preset_TelekomMobil"] = "Telekom Мобильный",

            ["Msg_ConfigLoaded"] = "Конфигурация успешно загружена.",
            ["ProfileSave_Title"] = "Сохранить профиль стратегии",
            ["ProfileSave_Header"] = "Найденные стратегии",
            ["ProfileSave_Desc"] = "Найдены следующие рабочие конфигурации. Выберите нужную и введите имя профиля.",
            ["ProfileSave_NameLabel"] = "Имя профиля:",
            ["Btn_Save"] = "Сохранить",
            ["Msg_SelectStrategy"] = "Пожалуйста, выберите стратегию из списка для сохранения.",
            ["Msg_EnterProfileName"] = "Пожалуйста, введите имя профиля.",
            ["Msg_ProfileNameEmpty"] = "Пожалуйста, введите действительное имя профиля.",
            ["Msg_ProfileSaved"] = "Профиль стратегии успешно сохранен и применен!",
            ["Msg_ProfileDeleted"] = "Профиль успешно удален.",
            ["Msg_ProfileDeleteTitle"] = "Удалить Профиль",
            ["Msg_ProfileDeleteConfirm"] = "Вы уверены, что хотите удалить профиль '{0}'?",
            ["Msg_SaveStrategyTitle"] = "Сохранить Стратегию",
            ["Msg_SaveStrategyPrompt"] = "Введите имя профиля для этой стратегии:",
            ["Msg_DefaultsRestoredTitle"] = "Восстановить по умолчанию",
            ["Msg_DefaultsRestoredConfirm"] = "Вы уверены, что хотите восстановить удаленные профили по умолчанию?",
            ["Msg_DefaultsRestoredSuccess"] = "Профили по умолчанию были успешно восстановлены.",
            ["Btn_RestoreDefaults"] = "По умолчанию",
            ["Log_FoundStrategies"] = "НАЙДЕННЫЕ СТРАТЕГИИ:",

            ["Msg_StrategySaved"] = "Стратегия успешно сохранена!",
            ["Msg_HostlistSaved"] = "Список hostlist сохранен.",
            ["Msg_ExcludelistSaved"] = "Список исключений сохранен.",
            ["Msg_ZapretCrash"] = "Процесс Zapret неожиданно завершил работу или аварийно упал.",
            ["Msg_ZapretStartFail"] = "Не удалось запустить движок Zapret или он сразу аварийно завершился.\r\nПожалуйста, проверьте пути к файлам и античит-программы.",
            ["Msg_DnscryptConflict"] = "Служба DNSCrypt в данный момент активна. Если вы установите другой DNS, DNSCrypt будет отключен. Вы хотите продолжить?",
            ["Msg_ServiceRemoved"] = "Служба ZapretService успешно остановлена и удалена.",
            ["Msg_ServiceInstalled"] = "Служба ZapretService успешно установлена и запущена в автозагрузке Windows!",
            ["Msg_ServiceStartFail"] = "Служба зарегистрирована, но не смогла запуститься. Возможно, открыта другая сессия WinDivert или требуется перезагрузка ПК.",
            ["Msg_ConflictDetected"] = "Обнаружены заблокированные фоновые процессы (winws2). Требуется перезагрузка системы.\n\nВы хотите перезагрузить компьютер сейчас?",
            ["Msg_DnscryptRemoved"] = "DNSCrypt удален, настройки DNS сброшены на авто (DHCP).",
            ["Msg_DnscryptInstalled"] = "Служба DNSCrypt установлена, системный DNS настроен на 127.0.0.1.",
            ["Msg_DnscryptFail"] = "Ошибка установки DNSCrypt.",
            ["Msg_DnscryptServerChanged"] = "Сервер DNSCrypt изменен, и служба перезапущена.",
            ["Msg_DnsGoogleSet"] = "Системный DNS настроен на Google DNS (8.8.8.8 / 8.8.4.4), кэш очищен.",
            ["Msg_DnsAdguardSet"] = "Системный DNS настроен на AdGuard DNS (94.140.14.14 / 94.140.15.15), кэш очищен.",
            ["Msg_DnsCloudflareSet"] = "Системный DNS настроен на Cloudflare (1.1.1.1 / 1.0.0.1), кэш очищен.",
            ["Msg_DnsQuad9Set"] = "Системный DNS настроен на Quad9 (9.9.9.9 / 149.112.112.112), кэш очищен.",
            ["Msg_DnsDhcpSet"] = "Настройки DNS сброшены на автоматические (DHCP).",
            ["Msg_NpcapNotFound"] = "Драйвер Npcap не найден в системе.\r\n\r\nNpcap необходим для раздачи сети (LAN) на приставки и Smart TV через Zapret.\r\n\r\nОткрыть страницу загрузки Npcap?",
            ["Msg_FirewallPrompt"] = "Требуется разрешение брандмауэра Windows для go-pcap2socks.\r\nНажмите 'Разрешить доступ' при появлении запроса.",
            ["Msg_AnalysisDoneWorking"] = "Анализ завершен!\r\n\r\nРабочая стратегия:\r\n{0}",
            ["Msg_AnalysisDoneTimeout"] = "Анализ завершен. Рабочая стратегия обхода DPI не найдена.",
            ["Msg_NoStrategiesFound"] = "Анализ завершен. Рабочая стратегия обхода DPI не найдена.",
            ["Msg_AnalysisTimeout"] = "Время анализа истекло (превышен лимит 12 минут).",
            ["Msg_DnsPoisonFound"] = "Обнаружен DNS-спуфинг со стороны провайдера!\r\n\r\nПереключить системный DNS на Google DNS (8.8.8.8 / 8.8.4.4)?",
            ["Title_DnsThreat"] = "Обнаружена угроза DNS",
            ["Title_DnsReport"] = "Диагностический отчет DNS",
            ["Title_CleanupDone"] = "Очистка завершена",
            ["Title_Firewall"] = "Брандмауэр",
            ["Title_CrashWarning"] = "Предупреждение о сбое Zapret",

            ["Btn_Ok"] = "ОК",
            ["Btn_Cancel"] = "Отмена",
            ["Btn_Yes"] = "Да",
            ["Btn_No"] = "Нет",
            ["Dialog_UpdateAvailableTitle"] = "Доступно обновление! 🚀",
            ["Dialog_UpdateFoundPrompt"] = "Выпущена новая версия ZapretDPI-TR {0}!\r\nТекущая версия: {1}\r\n\r\nХотите обновить сейчас?",
            ["Dialog_UpToDateTitle"] = "У вас последняя версия",
            ["Dialog_UpToDateText"] = "Вы используете последнюю версию ({0}). Обновлений не найдено.",
            ["Dialog_UpdateCheckFailed"] = "Не удалось проверить наличие обновлений.",
            ["Dialog_UpdateTitle"] = "Обновление",
            ["Dialog_ReleaseNotesTitle"] = "Что нового и список изменений",
            ["Dialog_BtnUpdateNow"] = "Обновить сейчас и перезапустить",
            ["Dialog_BtnLater"] = "Позже",
            ["Dialog_DownloadingUpdate"] = "Загрузка обновления...",
            ["Dialog_ApplyingUpdate"] = "Применение обновления...",
            ["Dns_CleanTag"] = "Чисто",
            ["Dns_PoisonedTag"] = "СПУФИНГ / ПОДДЕЛЬНЫЙ IP!",
            ["Dns_UnresolvedTag"] = "Не удалось разрешить",
            ["Dns_CleanSummary"] = "DNS-запросы полностью чистые и направляются на подлинные серверы. ({0}/{1} успешно)",
            ["Dns_PoisonedSummary"] = "Обнаружен DNS-спуфинг со стороны провайдера! Заблокированные сайты перенаправляются на поддельные IP.",
            ["Dns_TotalResponseTime"] = "Общее время ответа: {0} мс",
            ["Dns_DomainAnalysisDetails"] = "Детали анализа доменов",

            ["Status_Starting"] = "⏳ Запуск...",
            ["Status_Stopping"] = "⏳ Остановка...",
            ["Status_Installing"] = "⏳ Установка...",
            ["Status_Removing"] = "⏳ Удаление...",
            ["Status_Cleaning"] = "⏳ Очистка...",
            ["Status_Applying"] = "⏳ Применение...",
            ["Status_Testing"] = "⏳ Тестирование...",
            ["Btn_TestPoison"] = "Проверить DNS-спуфинг сейчас",

            ["ProfileSave_ApplyNow"] = "Сделать профилем по умолчанию и сразу запустить Zapret",
            ["Btn_SaveAndApply"] = "Сохранить и применить",
            ["Overview_ActiveProfileTitle"] = "Используемый DPI профиль",
            ["Overview_ActiveProfileDesc"] = "Выбранная стратегия применяется для запуска и службы Windows.",

            ["About_Title"] = "О программе",
            ["About_Subtitle"] = "Информация о версии ZapretDPI-TR, сведения о системе и лицензии.",
            ["About_Description"] = "Современный и компактный инструмент обхода DPI и управления маршрутизацией для Windows, движком Zapret2 LUA, безопасностью DNS и автоматическим анализом провайдера.",
            ["About_PlatformCardTitle"] = "Платформа и система",
            ["About_Platform"] = "Платформа:",
            ["About_Arch"] = "Архитектура:",
            ["About_Runtime"] = "Среда выполнения:",
            ["About_Language"] = "Язык интерфейса:",
            ["About_DpiCardTitle"] = "Ядро DPI и сеть",
            ["About_Core"] = "Ядро DPI:",
            ["About_Driver"] = "Драйвер пакетов:",
            ["About_Dns"] = "Шифрованный DNS:",
            ["About_Lan"] = "Раздача (LAN):",
            ["About_LicenseTitle"] = "Лицензия и уведомление об открытом исходном коде",
            ["About_License"] = "ZapretDPI-TR — это программное обеспечение с открытым исходным кодом, распространяемое под лицензией MIT. В проекте используются сторонние компоненты: Zapret2 (WinWS2), WinDivert, dnscrypt-proxy и go-pcap2socks. Авторские права принадлежат их владельцам.",
            ["About_BtnRepo"] = "Репозиторий проекта (GitHub)",
            ["Btn_CheckUpdates"] = "Проверить обновления"
        }
    };

    public static void SetLanguage(string lang)
    {
        if (Translations.ContainsKey(lang))
        {
            CurrentLanguage = lang;
            LanguageChanged?.Invoke();
        }
    }

    public static string Get(string key)
    {
        if (Translations.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            return val;

        if (Translations["tr"].TryGetValue(key, out var fallbackVal))
            return fallbackVal;

        return key;
    }
}


